### ISSUE TITLE
似乎读帖和分享都没有生效

### ISSUE THREAD

**Issue by lhllhx** [jianggaocheng/mihoyo-signin#1]
似乎读帖和分享都没有生效
ps:建议每条命令运行加延时，这么高强度的去打api，很容易风控的。
pps： 建议在readme里补充本地搭建的方法（把之前的复制回来就行了

**Comment by lhllhx** [comment]
啊 找到问题了 是没有配置stoken的问题，必须要有stoken才能完成阅读帖子和分享，如果不是从移动端抓包，还是需要login_ticket来获取stoken的，网页版是没有stoken的  
（我发现用之前的接口还是可以获取stoken的）
~~已经完全忘了那些接口我到底是怎么弄出来的了~~

**Comment by jianggaocheng** [comment]
@lhllhx 
我之前用了你的方法生成的 token😄，以为可以简化就改了token 那里的逻辑，发现确实不行，还是得按照你里面写的通过 login_ticket 来取得 token

随机延时和readme 改好啦
#e268ba8
