### ISSUE TITLE
大佬，方不方便对执行的结果做一个反馈

### ISSUE THREAD

**Issue by davidelectricfree** [jianggaocheng/mihoyo-signin#10]
大佬，方不方便对执行的结果做一个反馈，把执行成功或者失败的结果反馈到邮箱里面，或者其他消息接口里面。

**Comment by davidelectricfree** [comment]
另外，不知道能不能随机设定一个程序的运行时间，只要保证每天运行一次就好了，感觉每天都是固定的时间看帖什么的，担心被检测出来哈哈

**Comment by davidelectricfree** [comment]
可惜程序不是Python，就这样用着吧😂

**Comment by jianggaocheng** [comment]
@davidelectricfree GitHub Action 默认是支持运行失败发送邮件给 GitHub 账号邮箱的，不过目前 cookie 过期等 case 没有抛出异常，下一步会着手进行开发。

**Comment by jianggaocheng** [comment]
随机使用 GitHub Action 的话是不支持随机时间的，如果担心被检测更推荐使用本地运行的方式，时间上随机同时规避了使用 GitHub IP 请求被发现的几率。

PS. 看来现在用 Python 的人多啊，在考虑要不要学起来了。

**Comment by davidelectricfree** [comment]
> 
> 
> 随机使用 GitHub Action 的话是不支持随机时间的，如果担心被检测更推荐使用本地运行的方式，时间上随机同时规避了使用 GitHub IP 请求被发现的几率。
> 
> PS. 看来现在用 Python 的人多啊，在考虑要不要学起来了。

笑哭，好的，今天看到好像出了一个故障，但是action没有报错，也没有邮件
(node:2585) UnhandledPromiseRejectionWarning: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1549:19)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
