### ISSUE TITLE
workflow可以进行多个账号的任务吗..

### ISSUE THREAD

**Issue by xANoyU** [jianggaocheng/mihoyo-signin#11]
rt

**Comment by davidelectricfree** [comment]
我对js了解的很少，但是如果是github action只需要在step里面再做一个action就好了吧，再做一个cookie的secret值，不用动主程序的

**Comment by jianggaocheng** [comment]
@xANoyU , 可以复制 .github/workflows/main.yml 这样可以新建一个独立的 action 设置单独的运行时间等等。

感谢 @davidelectricfree
