### ISSUE TITLE
获取不到LoginTicket

### ISSUE THREAD

**Issue by DrMuda** [jianggaocheng/mihoyo-signin#19]
现在cookies不包含LoginTicket了，其他的本地缓存也没有这个值，这该怎么办呢

**Comment by jianggaocheng** [comment]
看了下现在网页上确实不适用 login_ticket 了，暂时没有发现好的方法继续去在网页上获取 Token 来进行签到。

不过看了下，App 端依然在使用 stuid, stoken, login_ticket 进行 API 请求，目前暂时建议通过抓包的方式来获取 App 请求的 cookie 吧（原来网页和 App 用一样的 token 有点奇怪，估计 Mihoyo 那边改了逻辑）。

**Comment by DrMuda** [comment]
> 看了下现在网页上确实不适用 login_ticket 了，暂时没有发现好的方法继续去在网页上获取 Token 来进行签到。
> 
> 不过看了下，App 端依然在使用 stuid, stoken, login_ticket 进行 API 请求，目前暂时建议通过抓包的方式来获取 App 请求的 cookie 吧（原来网页和 App 用一样的 token 有点奇怪，估计 Mihoyo 那边改了逻辑）。

了解了，那我抓包app吧
