### ISSUE TITLE
运行cookie.js提示"登录信息已失效,请重新登录"

### ISSUE THREAD

**Issue by Indexxq** [jianggaocheng/mihoyo-signin#20]
λ node cookie.js
Arguments: []
LoginTicket:  undefined
Login failed, 登录信息已失效，请重新登录

运行cookie.js后这样提示,想问一下应该如何登录呢,我已经抓包获取到了那三个参数的值,但不知道该如何使用,希望大佬能讲解一下,十分感谢

**Comment by jianggaocheng** [comment]
@Indexxq 

现在已经不能通过 cookie.js 来把 web cookie 转成 app cookie 了，如果你已经抓包获取了stuid、stoken、login_ticket

只需要直接运行 
```
COOKIE_STRING='stuid=*******;stoken=****************;login_ticket=********************;' node index.js
```
即可

**Comment by Indexxq** [comment]
![image](https://user-images.githubusercontent.com/44560118/135425071-9d52de62-1cf5-42d0-b2fb-f5ae37b4328f.png)
在node交互模式下运行这个命令会出现报错"Uncaught SyntaxError: Unexpected identifier",我在网上搜索了一下但没有找到解决方案,大佬可以帮忙看一下嘛

**Comment by Indexxq** [comment]
node index.js COOKIE_STRING='stuid=*******;stoken=****************;login_ticket=********************;'
这样运行的话会提示"环境变量 COOKIE_STRING 未配置，退出..."

不太清楚要咋搞了,请求大佬帮助

**Comment by jianggaocheng** [comment]
@Indexxq 
你用的是 Windows 的 CMD 运行的是吗？


在 windows cmd 需要使用这样的语句来执行

```
# 注意设置 COOKIE_STRING 不要加引号了，两行命令分成两句执行
set COOKIE_STRING=stuid=*******;stoken=****************;login_ticket=********************;

node index.js
```

**Comment by Indexxq** [comment]
@jianggaocheng 
明白了，谢谢大佬的讲解，十分感谢
