### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by q4w5e6** [jianggaocheng/mihoyo-signin#3]
签到【崩坏3】 unkonwn err
点赞【2735039 啊这】unkonwn err

**Comment by q4w5e6** [comment]
求问大佬有这个问题吗？

**Comment by jianggaocheng** [comment]
@q4w5e6 在 #2 应该已经修复了这个问题，COOKIE_STRING 的格式调整了下，你现在用的是 JSON 的格式的 {"stuid":"*******","stoken":"**************","login_ticket":"**************"}，还是普通格式的 'stuid=*******;stoken=****************;login_ticket=********************;'

新版的应该是 'stuid=*******;stoken=****************;login_ticket=********************;' 这种格式，如果还是老的格式，可以重新 run 一下 cookie.js

**Comment by q4w5e6** [comment]
好的，非常感谢！
