### ISSUE TITLE
login_ticket怎么获取？

### ISSUE THREAD

**Issue by NekoMua** [jianggaocheng/mihoyo-signin#31]
我的抓包软件里边能直接获取到stuid和stoken但是找不到login_ticket啊，难不成是DS？

**Comment by NNNNzs** [comment]
https://github.com/XiaoMiku01/miyoubiAuto

> 我的抓包软件里边能直接获取到stuid和stoken但是找不到login_ticket啊，难不成是DS？

https://github.com/XiaoMiku01/miyoubiAuto
