### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by OuJinSheng** [jianggaocheng/mihoyo-signin#8]
![image](https://user-images.githubusercontent.com/54573521/104848495-29cc1c00-5920-11eb-88f4-6aacd0dac85f.png)

**Comment by jianggaocheng** [comment]
使用 GitBash(mingw64) 或者 cygwin 的控制台程序来运行，

或者在 windows cmd 使用这样的语句来执行

```
# 注意设置 COOKIE_STRING 不要加引号了，两行命令分成两句执行
set COOKIE_STRING=stuid=xxxxxxxx

node index.js
```

**Comment by jianggaocheng** [comment]
@OuJinSheng

**Comment by OuJinSheng** [comment]
> @OuJinSheng

好的。
