### ISSUE TITLE
一直执行点赞和看帖

### ISSUE THREAD

**Issue by Algernon1968** [jianggaocheng/mihoyo-signin#9]
Workflow运行停不下来了，一直在不停地执行点赞和看帖，如图（大概运行了十分钟后被我取消了）[https://ftp.bmp.ovh/imgs/2021/02/8b3a597bb74a17a7.png](url)

**Comment by jianggaocheng** [comment]
@Algernon1968 
从你 PO 的图片来看，运行看起来是正常的？
目前的业务逻辑会对每个版块下面的 20 个帖子进行看帖和点赞操作，一般来说差不多 430多行日志后就会自动结束了，也许下次你可以再等一小会儿^_^

**Comment by Algernon1968** [comment]
> @Algernon1968
> 从你 PO 的图片来看，运行看起来是正常的？
> 目前的业务逻辑会对每个版块下面的 20 个帖子进行看帖和点赞操作，一般来说差不多 430多行日志后就会自动结束了，也许下次你可以再等一小会儿^_^

哇原来会执行这么多次吗？我还以为完成米游币任务后就会停止了，很抱歉问出这么没水平的问题😂非常感谢大大能抽出时间回答。

**Comment by jianggaocheng** [comment]
@Algernon1968 客气了~这样的设计是为了可以顺便刷频道等级哦，感谢你能发现问题提出来~~
